### ISSUE TITLE
configure

### ISSUE THREAD

**Issue by atlet16** [GitHubForSnap/ssmtp-gael#1]
Hi,
on RHEL8 is not created configuration file /var/snap/ssmtp-gael/current/ssmtp.conf after install ssmtp-gael. What is syntax of this file?
Thanx for help

**Comment by gael-legoff** [comment]
Hi Atlet16,

I didn't include any template or default ssmtp.conf as every configuration is different (depending on your needs).

You can read about the configuration options using:

`man ssmtp.conf`

or you can visit:

[man ssmtp.conf](https://linux.die.net/man/5/ssmtp.conf)

I use ssmtp to send emails through GMail servers, my config file looks like this: 

> root=<<YOUR_EMAIL_ADDRESS>>
> 
> mailhub=smtp.gmail.com:465
> 
> AuthUser=<<YOUR_USER>>@gmail.com
> AuthPass=<<YOUR_PASSWORD>>
> UseTLS=YES
> 
> rewriteDomain=gmail.com
> 
> hostname=<<COMPUTER_HOSTNAME>>
> 
> FromLineOverride=YES

If you created an alias for sendmail using this command:

`sudo snap alias ssmtp-gael.ssmtp sendmail`

You should be able to send emails with this command:

`echo "Subject: sendmail test" | sendmail -v <<YOUR_EMAIL_ADDRESS>>`

Best regards,
Gael

**Comment by atlet16** [comment]
Hi Gael,
it works!!! Thanks
